on:
  push:
    tags:
    - 'v*'

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print env
        run: |
          env
      - name: print tag
        run: |
          tag=(echo ${{ github.ref | cut -d/ -f3 }})
          echo $tag
#      - name: Docker Build and Push
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          platforms: linux/amd64
#          push: false
#          tags: |
#            ghcr.io/codenotary/immuproof:${{ github.ref }}
#            ghcr.io/codenotary/immuproof:latest
